### ISSUE TITLE
feat: Add swap and buy tabs on main interface

### ISSUE THREAD

**Issue by martinvibes** [Akshola00/cb3dex#18]
**Description**: To enhance the user experience and streamline token interactions, we’d like to add two distinct tabs, "Swap" and "Buy," to the main interface. By default, the "Swap" tab should be active when users first access this section.
**Note:** ` You can use the swap and buy tab screens on uniswap as sample`

### 1. Tab Layout:
  - Add two tabs labeled "Swap" and "Buy."
  - Position them side-by-side for easy navigation.

### 2. Default Tab:

  - The "Swap" tab should be the default view when this section is loaded.

### 3. Functionality for Each Tab:

  - The "Swap" tab will display the existing swap interface and features.
  - The "Buy" tab should open a new interface dedicated to purchasing tokens, following any existing UI/UX standards.

**Comment by Pvsaint** [comment]
Oya reassign am to me ASAP

**Comment by Akshola00** [comment]
@Pvsaint GM pls any progress on this
