### ISSUE TITLE
Implement token swap calculation function

### ISSUE THREAD

**Issue by Akshola00** [Akshola00/cb3dex#3]
### Goal
Develop a function to calculate the number of tokens a user will receive in exchange for a specified token amount on the DEX.

### Requirements
- The function should take as inputs:
  - `amountIn`: The amount of tokens the user wants to swap.
  - `tokenInAddress`: The contract address of the token the user wants to swap.
  - `tokenOutAddress`: The contract address of the token the user wants to receive.
- Implement logic to determine the exchange rate between `tokenIn` and `tokenOut`.
- Calculate the `amountOut`, which is the number of `tokenOut` tokens the user will receive based on the exchange rate.

**Comment by Iwueseiter** [comment]
I’d work on this
