### ISSUE TITLE
Implement Figma Design for Landing Page

### ISSUE THREAD

**Issue by Akshola00** [Akshola00/cb3dex#4]
### Goal
Implement the landing page according to the provided Figma design.

### Requirements
- Recreate the landing page layout, styles, and elements as per the Figma design.
- Ensure responsiveness across desktop, tablet, and mobile screen sizes.
- Follow component structures and spacing accurately to match the design.

### Figma Link
https://www.figma.com/proto/Cl1TvZwKBM9BOomCJGjsIa/Untitled?page-id=0%3A1&node-id=1-2&node-type=frame&viewport=629%2C222%2C0.71&t=oq5OhYCY6mDEsgIT-1&scaling=min-zoom&content-scaling=fixed

### Details
- Implement any animations or transitions specified in the design.
- Use the color scheme, typography, and spacing as provided in the Figma design.

### Development Notes
- Use Next.js and follow best practices for accessibility.
- Ensure CSS is modular, use tailwind CSS and decide on any UI library.
- If assets are needed (e.g., images, icons), download them from Figma or request assistance.

**Comment by Yunusabdul38** [comment]
i will love to work on this issue

**Comment by Akshola00** [comment]
> i will love to work on this issue

Start work asap pls
