### ISSUE TITLE
Connect Frontend to StarkNet and Implement Connect Wallet Feature

### ISSUE THREAD

**Issue by Akshola00** [Akshola00/cb3dex#6]
### Goal
Connect the frontend application to StarkNet using StarkNet React and implement a "Connect Wallet" feature for user interaction.

### Requirements
- Set up StarkNet React in the frontend project to allow interaction with StarkNet wallets.
- Implement a "Connect Wallet" button on the landing page (or header, as per design).
- Ensure the button:
  - Detects if the user has a StarkNet-compatible wallet installed.
  - Initiates the connection process when clicked.
  - Displays the user’s wallet address or a truncated version once connected.
- Handle cases where a user’s wallet is not available or they reject the connection.

### Acceptance Criteria
- The "Connect Wallet" button is visible and functional on the frontend.
- When clicked, the wallet connects successfully, displaying the wallet address.
- If a wallet is not detected, an appropriate message or prompt is shown.
- Disconnecting or reconnecting should update the UI accordingly.

**Comment by Yunusabdul38** [comment]
Gm 
i will loved to work on this issue
