### ISSUE TITLE
Implement Real-Time Token Pricing Mechanism for DEX

### ISSUE THREAD

**Issue by Akshola00** [Akshola00/cb3dex#9]
### Goal
Implement a dynamic pricing mechanism for tokens in the DEX based on current liquidity, allowing accurate and fair pricing for each swap transaction.

### Requirements
- **Pricing Model**: Use an Automated Market Maker (AMM) formula, such as the constant product formula (`x * y = k`), to determine token prices.
- **Dynamic Updates**: Ensure that token prices adjust automatically as liquidity changes due to swaps or liquidity pool modifications.
- **Swap Calculation Compatibility**: Integrate the pricing mechanism with the existing swap calculation function for accurate transaction processing.

**Comment by Kaminar-i** [comment]
Can I be assigned this

**Comment by Akshola00** [comment]
@Kaminar-i sorry about this but this issue has already been resolved 
my apologies for not closing it earlier
